### ISSUE TITLE
import slightly different module but cannot push feature branch

### ISSUE THREAD

**Issue by ambarb** [bluesky/hkl-notebooks#2]
@jklynch I altered one line of code to get the notebook working for me.  I stupidly did not realize that I would need to fork and only worked on a feature branch.  Just this once, can we coordinate opening for a feature branch PR/merge request?  I made the change so long ago, that I don't really remember and I just now sorted out the basics of access tokens.

**Comment by jklynch** [comment]
@ambarb maybe the problem was that you did not have full access to the repository. I have invited you to be an admin. You should get an email. Then I think you will be able to push your changes, no fork necessary.

**Comment by ambarb** [comment]
https://github.com/bluesky/hkl-notebooks/pull/3 was merged
